### ISSUE TITLE
Parallel computing cause MemoryError when memory is enough

### ISSUE THREAD

**Issue by Alsac** [trevorstephens/gplearn#179]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/gplearn/genetic.py", line 154, in _parallel_evolve
    program.raw_fitness_ = program.raw_fitness(X, y, curr_sample_weight) 
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/gplearn/_program.py", line 714, in raw_fitness
    y_pred = self.execute(X) ###this do function calculate with all features then get y_pred
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/gplearn/_program.py", line 614, in execute
    intermediate_result = function(*terminals)
  File "/home/wjs/anaconda3/lib/python3.6/site-packages/gplearn/functions.py", line 52, in __call__
    return self.function(*args)
MemoryError
"""

Hello! After hard-coding in _program.py and genetic.py, the program is worked to add time series func. However recently the program suffer MemoryError exception when memory is very enough in parallel computing.  I guess the bug may related to parallel.py, but I cannot find the solution.  Can you have any advice? I have try all my best to find reason, and exhausted😂

**Comment by Alsac** [comment]
Has solved!

**Comment by trevorstephens** [comment]
Sorry, busy week, what was the problem?

**Comment by Alsac** [comment]
Never mind! It is caused by a custom function, which  operate  may cause  error when suffer  nan  or  inf.😅

**Comment by trevorstephens** [comment]
Ah yep, glad you got it sorted!
