### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Alsac** [trevorstephens/gplearn#205]
Hey @trevorstephens !  
    Rencently, When I ran gplearn fitting, I always suffer MemoryError, even when n_jobs=1. my device memory is big enough about 700G, and the memory usage of all program is 50G lower. 
    so my question is <a>.what reason may cause this error? and <b>.how to fix it? 
    my env:  joblib 0.16.0, with python3.6 linux

Error log:
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    # We capture the KeyboardInterrupt and reraise it as
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/gplearn/genetic.py", line 154, in _parallel_evolve
    program.raw_fitness_ = program.raw_fitness(X, y, curr_sample_weight)  ######fitness section
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/gplearn/_program.py", line 725, in raw_fitness
    y_pred = self.execute(X) ###this do function calculate with all features then get y_pred
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/gplearn/_program.py", line 625, in execute
    intermediate_result = function(*terminals)#######this use the func
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/gplearn/functions.py", line 52, in __call__
    return self.function(*args)
MemoryError
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b04ff4d2c197>", line 223, in <module>
    est_gp.fit(X_train, y_train['y_normal'])
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/gplearn/genetic.py", line 513, in fit
    for i in range(n_jobs))
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    raise TimeoutError()
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/wangyanlong/anaconda3/envs/last_python/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
MemoryError

**Comment by hwulfmeyer** [comment]
MemoryError is not for your hard disk space but for your RAM.
See: https://www.pythonpool.com/python-memory-error/

Try lowering the population size or use the parameter `low_memory=True`.
