### ISSUE TITLE
Feature Request:  Saving / Loading a Model

### ISSUE THREAD

**Issue by ericbroda** [trevorstephens/gplearn#7]
In many cases one invests significant time/effort to fit/train the GP model.  Unfortunately, without a method of "saving" the model and "reloading" it from its save state, one is required to re-do the training of the model form its initial state.  This forces one to spend the same (significant) time/effort.

It would be ideal to:
(a) save the state of the model to a file
(b) load a model from a (state) file
(c) Incrementally update the loaded model with new data

This is a feature request.

**Comment by trevorstephens** [comment]
Hi @ericbroda ... Does pickling the object meet this need?

**Comment by ericbroda** [comment]
Yes it would.
I think pickling the file plus existing ability to view the model would probably be sufficient.
Can one pickle the model today?
 Best regards, Eric Brodamobile: 647.986.7017 | email: ericbroda@rogers.com | linkedin:  https://ca.linkedin.com/in/ericbroda

**Comment by ericbroda** [comment]
Trevor,
Not sure if you want to create a request in github, but I am getting the following error frequently when I run a length processing cycle (more than 20 generations) on a large data set. 

Thoughts?
*** ERROR ***Process ForkPoolWorker-95:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/Users/ericbroda/.virtualenvs/bnp-paribas-cardif-claims-mgmt/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 384, in put
    return send(obj)
  File "/Users/ericbroda/.virtualenvs/bnp-paribas-cardif-claims-mgmt/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 370, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/Users/ericbroda/.virtualenvs/bnp-paribas-cardif-claims-mgmt/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 384, in put
    return send(obj)
  File "/Users/ericbroda/.virtualenvs/bnp-paribas-cardif-claims-mgmt/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 370, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
 Best regards, Eric Brodamobile: 647.986.7017 | email: ericbroda@rogers.com | linkedin:  https://ca.linkedin.com/in/ericbroda

**Comment by trevorstephens** [comment]
@ericbroda as this is unrelated to the current issue, can you please open a new issue with a short reproducible example of this error? If you can reproduce using one of the scikit-learn dataset creation modules that would be great! Or at least the dataset shape (num features/rows) and the code you use to run the script.

**Comment by trevorstephens** [comment]
As for pickling, yes it is supported. Please try something like this and let me know if it closes this issue:

    from gplearn.genetic import SymbolicRegressor
    from sklearn.utils.random import check_random_state
    import numpy as np
    import pickle

    rng = check_random_state(0)

    # Training samples
    X_train = rng.uniform(-1, 1, 100).reshape(50, 2)
    y_train = X_train[:, 0]**2 - X_train[:, 1]**2 + X_train[:, 1] - 1

    # Testing samples
    X_test = rng.uniform(-1, 1, 100).reshape(50, 2)
    y_test = X_test[:, 0]**2 - X_test[:, 1]**2 + X_test[:, 1] - 1

    est_gp = SymbolicRegressor(population_size=5000,
                               generations=20, stopping_criteria=0.01,
                               comparison=False, transformer=False, 
                               p_crossover=0.7, p_subtree_mutation=0.1,
                               p_hoist_mutation=0.05, p_point_mutation=0.1,
                               max_samples=0.9, verbose=1,
                               parsimony_coefficient=0.01, random_state=0)
    est_gp.fit(X_train, y_train)

    trained_model = pickle.dumps(est_gp)
    model = pickle.loads(trained_model)

**Comment by trevorstephens** [comment]
> I think pickling the file plus existing ability to view the model would probably be sufficient.

And what do you mean by viewing the model exactly?

**Comment by ericbroda** [comment]
Trevor,
When I say "visualize", I am referring to the output (__str__) that provides something like the following:
[max(min(inv(X0), abs(X9)), X0),
 neg(sub(neg(abs(add(X5, X9))), inv(sub(sub(X4, X3), sqrt(X14))))),
 inv(min(neg(div(X13, X1)), X14)),
 neg(inv(add(add(sqrt(X13), sub(X8, X8)), min(sqrt(X9), neg(X2))))),
 add(X0, X2),
 log(min(max(inv(X11), neg(X0)), div(max(X10, X1), min(X3, X0)))),
 div(sub(sqrt(X4), mul(X9, X13)), max(X3, X3)),
 mul(X1, div(X5, X2)),
 min(X2, X9),
 abs(X3),
 min(X2, div(X3, 0.498)),
 neg(X11),
 abs(div(sqrt(X11), min(add(X0, X0), -0.772))),
 inv(X9),
 min(inv(inv(X1)), log(X9)),
 add(sqrt(X2), add(X9, X14)),
 sub(sub(X0, -0.615), abs(X0)),
 max(log(0.780), add(X5, X9)),
 sqrt(div(log(neg(X0)), div(X11, max(X11, X13)))),
 X9]

With this info I can get an idea of what the algorithm is doing. Best regards, Eric Brodamobile: 647.986.7017 | email: ericbroda@rogers.com | linkedin:  https://ca.linkedin.com/in/ericbroda

**Comment by trevorstephens** [comment]
Fixed by e84c788
