### ISSUE TITLE
Broken Pipe Issue

### ISSUE THREAD

**Issue by ericbroda** [trevorstephens/gplearn#8]
When fitting large datasets, frequently errors related to broken pipes occur.  

I have not yet been able to consistently reproduce the error but my dataset characteristics are listed below:
- number of rows:  143,000
- number of columns: 160

The gplearn configuration is as follows:

    gp = SymbolicTransformer(metric='spearman', generations=30,
                                 population_size=2500,
                                 hall_of_fame=100, n_components=10,
                                 parsimony_coefficient=0.0005,
                                 max_samples=0.9, verbose=1,
                                 random_state=0, n_jobs=4)

(I am running gplearn in a Mac environment)

The stack trace is listed below:

***
Process ForkPoolWorker-95:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/{myenv}/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 384, in put
    return send(obj)
  File "/{myenv}/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 370, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/{myenv}/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 384, in put
    return send(obj)
  File "/{myenv}/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 370, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by trevorstephens** [comment]
Thanks for the report. Possibly related to #5 ... Will look into it for the next release.

**Comment by trevorstephens** [comment]
I suspect that this issue is related to the serializing of all the indices lists for larger datasets while aggregating all the pool workers in joblib/multiprocessing but have been unable to reproduce it. This should be greatly alleviated by #19 ... If you still run into this issue when working from the master branch and/or the next release, please re-open this issue.
